blueprint:
  name: SmartScreen 天气数据推送
  description: 将天气实体数据通过 MQTT 推送到 SmartScreen
  domain: automation
  input:
    weather_entity:
      name: 天气实体
      description: 选择要推送的天气实体
      selector:
        entity:
          domain: weather
    mqtt_topic:
      name: MQTT 主题
      description: 推送的 MQTT 主题
      default: smartscreen/weather/state
      selector:
        text:
    update_interval:
      name: 更新间隔（分钟）
      description: 定时推送的间隔时间
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: 分钟

trigger:
  - platform: state
    entity_id: !input weather_entity

  - platform: time_pattern
    minutes: !input update_interval

variables:
  weather_entity: !input weather_entity
  mqtt_topic: !input mqtt_topic

action:
  - service: mqtt.publish
    data:
      topic: "{{ mqtt_topic }}"
      retain: true
      payload: >
        {% set s = states[weather_entity] %}
        {% set a = s.attributes %}

        {# --- 动态构建 attributes 字段 --- #}
        {% set attrs = dict() %}

        {% if 'temperature' in a %}
          {% set attrs = attrs | combine({'temperature': a.temperature}) %}
        {% endif %}

        {% if 'humidity' in a %}
          {% set attrs = attrs | combine({'humidity': a.humidity}) %}
        {% endif %}

        {% if 'skycon' in a %}
          {% set attrs = attrs | combine({'skycon': a.skycon}) %}
        {% endif %}

        {% if 'condition_cn' in a %}
          {% set attrs = attrs | combine({'condition_cn': a.condition_cn}) %}
        {% endif %}

        {% if 'qweather_icon' in a %}
          {% set attrs = attrs | combine({'qweather_icon': a.qweather_icon}) %}
        {% endif %}

        {% if 'friendly_name' in a %}
          {% set attrs = attrs | combine({'friendly_name': a.friendly_name}) %}
        {% endif %}

        {{
          {
            'state': s.state,
            'temperature': a.temperature if 'temperature' in a else None,
            'friendly_name': a.friendly_name if 'friendly_name' in a else '',
            'attributes': attrs
          } | tojson
        }}

mode: single
